### ISSUE TITLE
Vcontrold direkt als "Dienst" / Server im ioBroker?

### ISSUE THREAD

**Issue by Triton-KS** [misanorot/ioBroker.viessmann#100]
Hallo,
leider habe ich meine funktionierende Vcontold-SD-Karte überschrieben.
Seitdem bekomme ich auf meinem Raspberry Pi 4 mit Bullseye den VControld nicht mehr zum Laufen. (war vorher auf einen Raspberry Pi3) Zudem bin ich gerade frisch zum ioBroker gewechselt und arbeite micht gerade hier vor.
Dabei habe ich auch diesen Viessmann Adapter entdeckt. Leider kann ich nicht programmieren.

Wäre es möglich den ioBroker Adapter auch als Vcontrold-Server zu prgrammieren oder laufen zu lassen?
Also bei der Adapter-Installation auch den VControld Demon mit zu installieren. 
Einstellungen wie auf anderen Host, Lokal (über /dev/ttyUSB0 oder andere "Ports") erreichbar wären super.

Danke schonmal für die möglichen Antworten

**Comment by misanorot** [comment]
Hallo,

da bin ich selbst auch überfragt, denke aber das es nicht möglich ist. Davon mal abgesehen, wird das in den allermeisten Fällen auch nicht gehen, da ihr ioBroker Server nicht an der Heizung steht.
