### ISSUE TITLE
Adapter gets stopped by IOBROKER due to restart loop

### ISSUE THREAD

**Issue by R21-Ni** [misanorot/ioBroker.viessmann#110]
**Describe the bug**  
Since update to Nodejs 18 and JS-Controller 4.0.24, Adapter gets regularly stopped by IOBROKER due to detected restart loop. Usually happens after 6-72 h of operation. The below mentioned error occurs several times, leading to adapter restart. After 5 restart attempts adapter gets stopped by IOBRKOER System

**Logfiles**  
viessmann.0 | 2023-04-24 22:25:56.573 | error | this.setStateAsync is not a function
-- | -- | -- | --
viessmann.0 | 2023-04-24 22:25:56.572 | error | TypeError:  this.setStateAsync is not a function    at Timeout.main [as _onTimeout]  (/opt/iobroker/node_modules/iobroker.viessmann/main.js:584:8)    at  listOnTimeout (node:internal/timers:569:17)    at process.processTimers  (node:internal/timers:512:7)
viessmann.0 | 2023-04-24 22:25:56.571 | error | unhandled promise rejection: this.setStateAsync is not a function
viessmann.0 | 2023-04-24 22:25:56.570 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

**Versions:**  
 - Adapter version: 1.43
 - JS-Controller version: 4.0.24
 - Node version: v18.15.0

**Comment by misanorot** [comment]
Hello,

I updated my system to the same Versions. I will see if the same problems occur the next days.

**Comment by misanorot** [comment]
Hello,

I dont have this issues with the same setup. Plaese give me more logs.

**Comment by Huskerdu24** [comment]
The same probleme here. The adapter did not connect to the host anymore. After several attemps, the host stops the adapter.

`<html><body>


viessmann.0 | 2023-06-14 21:24:42.452 | info | terminating
-- | -- | -- | --
viessmann.0 | 2023-06-14 21:24:41.949 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
viessmann.0 | 2023-06-14 21:24:41.947 | info | terminating
viessmann.0 | 2023-06-14 21:24:41.945 | info | cleaned everything up...
viessmann.0 | 2023-06-14 21:24:41.913 | info | Connect with Viessmann sytem!
viessmann.0 | 2023-06-14 21:24:41.889 | error | Parameter "options" needs to be a real object but type "boolean" has been passed
viessmann.0 | 2023-06-14 21:24:41.888 | error | Error:  Parameter "options" needs to be a real object but type "boolean" has  been passed     at Validator.assertObject  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/validator.js:215:19)     at Viessmann.setState  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5331:35)     at  /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2007:16     at new Promise (<anonymous>)     at Viessmann.setStateAsync  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2006:16)     at Viessmann.main  (/opt/iobroker/node_modules/iobroker.viessmann/main.js:588:8)     at Viessmann.startAdapter  (/opt/iobroker/node_modules/iobroker.viessmann/main.js:116:15)     at Viessmann.onReady  (/opt/iobroker/node_modules/iobroker.viessmann/main.js:55:9)     at Viessmann.emit (node:events:513:28)     at Viessmann._callReadyHandler  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9017:18)
viessmann.0 | 2023-06-14 21:24:41.878 | error | unhandled promise rejection: Parameter "options" needs to be a real object but type "boolean" has been passed
viessmann.0 | 2023-06-14 21:24:41.876 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
viessmann.0 | 2023-06-14 21:24:41.735 | info | starting. Version 1.4.3 in /opt/iobroker/node_modules/iobroker.viessmann, node: v18.16.0, js-controller: 5.0.3


</body>
</html>`

Versions:
    Adapter version: 1.4.3
    JS-Controller version: 5.0.3
    Node version: v18.16.0
    NPM: 9.5.1
