### ISSUE TITLE
Adapter is not working, strange warnings in the log

### ISSUE THREAD

**Issue by t4qjXH8N** [misanorot/iobroker.viessmann#13]
Dear folks,

I have a strange error here. Vcontrold is setup up correctly, I can connect to it via telnet, issue commands and receive values. Converting the vito.xml into JSON worked and the adapter said everything was fine. All functions can be accessed via the admin interface. For testing purposes, I wanted to read out only one value each minute. But when using iobroker, the daemon hangs and the following lines are plotted to the log

`viessmann.0	2017-02-20 15:47:41.680	warn	viessmann.0 No states found for {"type":"state","common":{"name":"","desc":"Testabfrage, Adresse eingeben"},"native":{},"_id":"viessmann.0.get."}'
'viessmann.0	2017-02-20 15:47:41.430	warn	vctrld>'
'viessmann.0	2017-02-20 15:47:41.430	warn	Vctrld send ERROR: vctrld>ERR: command unknown`

Any ideas?

**Comment by t4qjXH8N** [comment]
Ok, the problem is more complex.
The vcontrold is running on a Raspburry PI. When I debug the adapter on my laptop and connect to the vcontrold daemon, the states are filled with values. When I start the same instance on the PI connecting to localhost (I don't think the type of connection matters), I get the following warning

'viessmann.0	2017-02-20 19:14:15.133	warn	Malfunction connection'

**Comment by misanorot** [comment]
Hi,

Delete in your Vito.xml the command it call get.

Example:

<command name="get" protocmd="gettestaddr">
<description>Testabfrage, Adresse eingeben</description>
<device ID="2053">
<addr>dummy</addr>
<len>1</len>
</device>
</command>

**Comment by t4qjXH8N** [comment]
Hey, 
thank you very much for your help. But I'm sorry, it is still not working. I reinstalled the adapter and double checked that any previous version/cache etc. was removed. Then I tried a JSON with only two entries (a try with one entry led to #15 ) . This is my JSON

```
{
  "vito": {
    "devices": {
      "device": {
        "-ID": "20CB",
        "-name": "V200KW2",
        "-protocol": "KW2"
      }
    },
    "commands": {
      "command": [
        {
          "-name": "getHeizkreisPumpeA1",
          "-protocmd": "getaddr",
          "addr": "7663",
          "len": "1",
          "unit": "RT",
          "description": "Status Heizkreispumpe A1"
        },
        {
          "-name": "getTempA",
          "-protocmd": "getaddr",
          "addr": "5525",
          "len": "2",
          "unit": "UT",
          "error": "05 05",
          "description": "Aussentemperatur"
        }
      ]
    }
  }
}
```

Sorry, it is not working.  There is still the warning

`viessmann.0	2017-02-21 20:15:51.487	warn	Vctrld send ERROR: vctrld>ERR: command unknown`

in the log,

**Comment by t4qjXH8N** [comment]
Finally the problem was solved by removing the string "dummy\n" that was send upon connection. I reverted my changes concerning the double backslashes in #14 and simply removed the line in #14. It seems that sending this string confused the vcontrold demon. 
Thanks you very much for your help!
