### ISSUE TITLE
Fehler beim Bearbeiten eines Wertes

### ISSUE THREAD

**Issue by Matze2010** [misanorot/ioBroker.viessmann#143]
Wenn ich versuche, im Objektbrowser einen Setzdatenpunkt zu ändern, erscheint immer folgende Fehlermeldung:

<img width="500" alt="Bildschirmfoto 2023-09-01 um 05 18 34" src="https://github.com/misanorot/ioBroker.viessmann/assets/203814/7f69901a-3f1e-4d0f-99d0-4de1851bf709">

**Comment by misanorot** [comment]
Was willst du ändern? Und welchen Baum meinst du, iobroker?

**Comment by Matze2010** [comment]
Ich habe in den Einstellung des viessmann-Adapters verschiedene Setzdatenpunkte eingerichtet. Egal bei welchem dieser Datenpunkte ich denWert ändern möchte, immer erscheint die Fehlermeldung. Zum Beispiel wollte ich die NeigungM1 erhöhen. Der Datenpunkt wird vom viessmann-Adapter wie folgt einrichtet:

```
{
  "type": "state",
  "common": {
    "name": "NeigungM1",
    "unit": "",
    "type": "number",
    "desc": "Setze Neigung Heizkennlinie M1",
    "read": true,
    "write": true
  },
  "native": {},
  "from": "system.adapter.viessmann.0",
  "user": "system.user.admin",
  "ts": [1693537636471](tel:1693537636471),
  "_id": "viessmann.0.set.NeigungM1",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by misanorot** [comment]
Was sagt den der iobroker log? Im Notfall die Instanz mal auf debug stellen.

**Comment by misanorot** [comment]
ich gehe davon aus, dass kein weiterer Bedarf besteht.....
