### ISSUE TITLE
Häufige Abstürze des Adapters

### ISSUE THREAD

**Issue by martinschm** [misanorot/ioBroker.viessmann#157]
**Describe the bug**  
Seit einiger Zeit stürzt der Adapter sehr häufig ab und wir dann von iobroker gestoppt.
Der Adapter logt sich ber SSH auf meinem Raspberry im Keller ein und holt die Daten dort ab.

**To Reproduce**  
Starten, Warten, Adapter stürzt ab

**Screenshots & Logfiles**  
Hab die Log Stufe schon auf Debug, mehr steht leider trotzdem nicht drin.
```
viessmann.0 | 2023-11-18 20:54:19.870 | info | terminating
-- | -- | -- | --
viessmann.0 | 2023-11-18 20:54:19.368 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
viessmann.0 | 2023-11-18 20:54:19.365 | info | terminating
viessmann.0 | 2023-11-18 20:54:19.364 | info | cleaned everything up...
viessmann.0 | 2023-11-18 20:54:19.357 | error | this.setState is not a function
```

**Versions:**  
Adapter 1.4.6
js-controller: 5.0.12
node.js v18.17.1

**Comment by misanorot** [comment]
Hallo, da müsste mehr stehen. Starte den PI mal neu, vom Adapter kommt das eher nicht

**Comment by martinschm** [comment]
Hi,
hab den PI neu gestartet und beobachte mal.

Allerdings verstehe ich nicht, wie es am PI liegen kann, wenn der Adapter der auf einem anderen Rechner läuft ständig abstürzt. Der Adapter logt sich doch ber SSH ein und liest Daten aus. Wenn irgendwas schief geht sollte der Adapter das doch auffangen und nicht abstürzen, oder ?

**Comment by RaiSchm** [comment]
Moin,
 
ich hatte auch Abstürze (kurz nach der 1. Installation).    Bei mir ist übrigens ioBroker  auf dem PI wo auch der vClient/vControld liegt.
Nachdem ich meinen eigenen python Dienst, der alle 10 sec Abfragen geschickt hatte um nach csv zu loggen, abgestellt hatte, gab es auch keine Abstürze im ioBroker mehr.     Mein Dienst loggte übrigens Schrott, wenn gleichzeitig ioBroker mit dem Adapter lief.

Mit ioBroker und influxdb  erscheint mir die Lösung viel viel Eleganter! Läuft seit 2 Tagen stabil.

Ich denke es liegt am vControl dass er nicht von mehreren "Clients"  stabil benutzt werden kann.

**Comment by misanorot** [comment]
Hallo, bin zwar nicht der absolute vcontrold Experte, aber mehrfache Zugriffe und oder zu viel  Abfragen sind nicht gut und führen zu Problemen.

Ich schließe den issue, falls doch noch was ist, bitte wieder melden. Beste Grüße
