### ISSUE TITLE
Invalide Werte ignorieren

### ISSUE THREAD

**Issue by ThorstenBoettler** [misanorot/ioBroker.viessmann#163]
**Describe the bug**  
Werte die invalide sind ignorieren

**To Reproduce**  
Wenn durch einen Lesefehler z.B. 0505 Zurück kommt und dieser Wert eine Temperatur ist (value/10), wird in das Objekt 128,5°C geschrieben.  

**Expected behavior**  
Das diese Werte ignoriert werden, entweder generell oder man kann die Datenpunkte markieren bei denen das so sein soll.

**Versions:**  
 - Adapter version: 1.4.6

**Comment by misanorot** [comment]
Hallo,

kannst du das nochmal etwas näher beschreiben? Stehe gerade etwas auf dem Schlauch.....

**Comment by misanorot** [comment]
da keine Antwort, mache ich es erstmal zu....
