### ISSUE TITLE
Sending time for request via "force polling interval"

### ISSUE THREAD

**Issue by TwinFlex** [misanorot/ioBroker.viessmann#211]
**Describe the bug**  
A "force polling interval" request for a certain get command (i.e. getTempA) is not sent out directly, but is waiting for the next scheduled run. Depending on the schedule settings for other get commands it can take up to 60 s (heartbeat interval) before the "force polling interval" request is executed.

**To Reproduce**  
1. All "get commands" with interval 2 min. cycle time
2. Send "force polling request" -> getTempA

Log:
2024-08-02 07:43:18.372 - debug: viessmann.0 (2748) Wait for next run: 59259 in ms -> Timer
2024-08-02 07:43:25.562 - info: viessmann.0 (2748) Force polling interval: getTempA
2024-08-02 07:44:17.633 - debug: viessmann.0 (2748) Next poll: getTempA (For Object: TempA)
2024-08-02 07:44:17.691 - debug: viessmann.0 (2748) Received: 21.200001 Degrees Celsius

**Expected behavior**  
Force Polling is executed directly after request

**Hints**
A workaround would be, to set at least on "get command" to the minimum cycle time value of 2 s. 
But was wondering if this is the expacted behavior of the "force polling interval" function

**Comment by misanorot** [comment]
Hello, I will check this tipic the next days.

**Comment by misanorot** [comment]
Bitte mal die Github Version testen und Feedback geben, ich habe leider keine Zeit zum testen. DANKE
