### ISSUE TITLE
Adapter configuration

### ISSUE THREAD

**Issue by mhandschuher** [misanorot/ioBroker.viessmann#26]
Change adapter to read vito.xml from vcontrold configuration (/etc/vcontrold/vito.xml) as the adapter presumes a running vcontrold (really not necessary to have the vito.xml twice).

In addition, add function to reload configuration while instance is already present (it's really awful if you have to change something within the vito.xml and have to delete the instance first and reconfigure everything afterwords!)

**Comment by misanorot** [comment]
First part is done.

Second, it is not so easy but i try it the next weeks.
