### ISSUE TITLE
Datenpunkte werden nicht aus Vito.xml übernommen

### ISSUE THREAD

**Issue by xyronx** [misanorot/ioBroker.viessmann#27]
Einlesen der Vito.xml über ssh funktioniert, jedoch werden Abfrage- und Setzdatenpunkte nicht in der Instanzkonfiguration aktualisiert.

**Comment by misanorot** [comment]
Hallo,

Werden die allgemeinen Informationen in der Konfigseite angezeigt? Bitte Mal debug Ausgabe posten

**Comment by xyronx** [comment]
Es werden die allgemeinen Datenpunkte angezeigt, aber nicht meine persönlichen aus meiner vito.xml. 
Dementsprechend bekomme ich bei der Abfrage einen Fehler, da meine Befehle anders lauten.
Debug:

viessmann.0 | 2018-10-02 18:47:30.633 | debug | Wait for next run: 29989 in ms
viessmann.0 | 2018-10-02 18:47:30.632 | warn | Vctrld send ERROR: ERR: command unknown
viessmann.0 | 2018-10-02 18:47:30.622 | debug | Next poll: getTempAussen TempAussen
viessmann.0 | 2018-10-02 18:47:00.636 | debug | Wait for next run: 30000 in ms
viessmann.0 | 2018-10-02 18:47:00.635 | info | Connect with Viessmann sytem!
viessmann.0 | 2018-10-02 18:47:00.609 | debug | Commands for polling: getTempAussen
viessmann.0 | 2018-10-02 18:47:00.609 | info | starting. Version 0.6.1 in /opt/iobroker/node_modules/iobroker.viessmann, node: v8.11.3
viessmann.0 | 2018-10-02 18:46:56.622 | info | Connection with Viessmann system disconnected!
viessmann.0 | 2018-10-02 18:46:56.621 | info | cleaned everything up...
viessmann.0 | 2018-10-02 18:46:56.592 | debug | Wait for next run: 30000 in ms
viessmann.0 | 2018-10-02 18:46:56.592 | info | Connect with Viessmann sytem!
viessmann.0 | 2018-10-02 18:46:56.591 | debug | SSH connection closed
viessmann.0 | 2018-10-02 18:46:56.591 | debug | Commands for polling: getTempAussen
viessmann.0 | 2018-10-02 18:46:56.590 | info | read vito.xml successful
viessmann.0 | 2018-10-02 18:46:55.742 | debug | FTP session ready
viessmann.0 | 2018-10-02 18:46:55.238 | debug | try to create a ssh session
viessmann.0 | 2018-10-02 18:46:55.238 | debug | try to read xml
viessmann.0 | 2018-10-02 18:46:55.238 | info | starting. Version 0.6.1 in /opt/iobroker/node_modules/iobroker.viessmann, node: v8.11.3

**Comment by misanorot** [comment]
Hallo,

du hattest vorher die 0.5.x Version installiert, dort hatte ich versehentlich meine xml bei NPM mit hochgeladen! 

Bitte deinstallieren, und die aktuelle Version installieren. Alternativ, die Vito.xml aus dem Adapter Verzeichnis löschen, und die Werte neu einlesen.
