### ISSUE TITLE
Problem with negative Values

### ISSUE THREAD

**Issue by baresel** [misanorot/ioBroker.viessmann#29]
I configured the viessman connector ad can read the values from vcontrold using a local vito.xml. If i get positive values from the Kolektor Temperature it is working with sql history adapter, becasue the values are shown as numbers only. but if vcontrold returns a negative temperature, the number and a string "Grad Celsius" is shown, which isnt only a number anymore. This is occurs only on negative temperture values:
Error in iobroker.log:
sql.0 2018-10-31 06:11:55.005 info Do not store value "-1.500000 Grad Celsius" for viessmann.0.get.TempKol because no number

Is this a problem within the adapter or in vcontrold ?

**Comment by foxriver76** [comment]
@misanorot for further information have a look at https://forum.iobroker.net/viewtopic.php?f=22&t=17844#p188967

**Comment by misanorot** [comment]
> I configured the viessman connector ad can read the values from vcontrold using a local vito.xml. If i get positive values from the Kolektor Temperature it is working with sql history adapter, becasue the values are shown as numbers only. but if vcontrold returns a negative temperature, the number and a string "Grad Celsius" is shown, which isnt only a number anymore. This is occurs only on negative temperture values:
> Error in iobroker.log:
> sql.0 2018-10-31 06:11:55.005 info Do not store value "-1.500000 Grad Celsius" for viessmann.0.get.TempKol because no number
> 
> Is this a problem within the adapter or in vcontrold ?

Please install the Github Version. I hope it is fixed.
