### ISSUE TITLE
Please integrate VitoConnect API

### ISSUE THREAD

**Issue by AlexanderSch90** [misanorot/ioBroker.viessmann#30]
Please let this adapter working with the viessmann api. 
Check: https://github.com/thetrueavatar/Viessmann-Api/blob/develop/README-en.md

Thanks!

**Comment by misanorot** [comment]
Hey,  currently it is to high for me. The other thing is, it is better to create a new adapter like "Viessmann-Cloud" or what ever.  I observe this topic in the future continue and than we will see....
