### ISSUE TITLE
SSH Verbindung mit RSA Key

### ISSUE THREAD

**Issue by XerXes777** [misanorot/ioBroker.viessmann#31]
Was mache ich, wenn vcontrold auf einem Raspberry läuft
und die Verbindung kann nur mit einem RSA Key aufgebaut werden?

**Comment by misanorot** [comment]
Was ist das? Und warum geht keine "normale" SSH Verbindung?

**Comment by misanorot** [comment]
Okay, habe mich auch kurz eingelesen, allerdings weiß ich nicht wie ich das realisieren soll. Zumindest nicht auf die schnelle. 
Als Workaround, lege dir auf deinem Iobroker Master einen Ordner an, packe beide Files dort rein, und gib den Pfad bei den Adapter Settings an.

PS: Da das im eigentlichen sinne kein Issue ist, schließe ich dieses.
