### ISSUE TITLE
Setzdatenpunkte nicht verfügbar 

### ISSUE THREAD

**Issue by FM-500** [misanorot/ioBroker.viessmann#34]
Hallo,

Adapter läuft bei mir mit einigen Werten und Lesen funktioniert .

Ich würde allerdings gerne die 1xWW Funktion triggern, also setzen.

Sehe aber in der Oberfläche keine Setzdatenpunkte.

Habe auch schon mehrere Vito.xml versucht...

**Comment by misanorot** [comment]
Hallo,

Werden die Set Werte denn überhaupt eingelesen? Müssten in der Adapter Konfiguration zu sehen sein.

**Comment by misanorot** [comment]
Ggf mir bitte die Vito schicken

**Comment by FM-500** [comment]
Hallo und danke für die Antwort.
War unterwegs, daher erst jetzt wieder.

Die Set-Werte werden nicht eingelesen, daher vermute ich auch eine falsche vito.xml, kann mir da aber nicht helfen.

Habe zum Test mal nur Außentemperatur und 1x Warmwasser hinterlegt. Das ist der einzige Setzwert, den ich brauche.
Die Adresse dafür ist B020 ich weiß aber nicht, wie ich das command als Setzwert markieren kann.

Laut Viessmann Community muss ich den Wert auf 2 setzen, damit die einmalige WW-Bereitung gestartet wird...

Anbei die Screenshots aus ioBroker un die aktuell eingesetzte vito.xml
vito.txt bitte in XML umbenennen ich konnte sie nicht hochladen.

Danke schon vorab!

`<vito>
        <devices>
                <device ID="204D" name="V200WO1C" protocol="P300"/>
        </devices>
        <commands>
			<command name="getDevType" protocmd="getaddr">
				<addr>00F8</addr>
				<len>2</len>
				<unit>UN</unit>
				<description>Information - Allgemein: Anlagentyp (204D)</description>
			</command>
				<command name="getTempA" protocmd="getaddr">
				<addr>0101</addr>
				<len>2</len>
				<unit>UT</unit>
				<description>Information - Allgemein: Aussentemperatur (-40..70)</description>
				</command>
			<command name="getWWEinmal" protocmd="getaddr">
				<addr>B020</addr>
				<len>1</len>
				<unit>RT</unit>
				<description>Bedienung WW - Betriebsdaten WW: 1x WW-Bereitung (0..1)</description>
			</command>
			<command name="getWWEinmal" protocmd="setaddr">
				<addr>B020</addr>
				<len>1</len>
				<unit>RT</unit>
				<description>Bedienung WW - Betriebsdaten WW: 1x WW-Bereitung (0..1)</description>
			</command>
        </commands>
</vito>`

[vito.txt](https://github.com/misanorot/ioBroker.viessmann/files/2942607/vito.txt)

<img width="1781" alt="0x-objects" src="https://user-images.githubusercontent.com/40071240/53977792-1c319280-410a-11e9-8d65-19ce160559fe.png">
<img width="1776" alt="00-general" src="https://user-images.githubusercontent.com/40071240/53977794-1c319280-410a-11e9-9062-6c8c86959369.png">
<img width="1776" alt="01-abfrage" src="https://user-images.githubusercontent.com/40071240/53977795-1c319280-410a-11e9-9495-00cf538798ef.png">
<img width="1784" alt="02-setzen" src="https://user-images.githubusercontent.com/40071240/53977797-1cca2900-410a-11e9-89a9-144cc9f3f1ae.png">

**Comment by misanorot** [comment]
Hi,

also ohne einen konfigurierten Setzwert in der Vito wird das nichts.
Ein Setzwert muss immer mit set beginnen.

Ich mache den issue zu. Bei fragen bitte weiter im Forum nachfragen, da ich von den Vitos auch keine wirkliche Ahnung habe.
