### ISSUE TITLE
Vctrld send ERROR: ERR: command unknown

### ISSUE THREAD

**Issue by XerXes777** [misanorot/ioBroker.viessmann#41]
Ich bekomme immer wieder diese Meldung bei iobroker im Log.
Und meine Daten bei den Objekten stimmen dann nicht mehr (siehe Bild):

Was mache ich falsch ?

<img width="1160" alt="Bildschirmfoto 2019-06-11 um 11 29 42" src="https://user-images.githubusercontent.com/28979354/59260927-d1f60b00-8c3c-11e9-9c7e-2f2e3de0bcf0.png">

[viesman_adapter.log](https://github.com/misanorot/ioBroker.viessmann/files/3275703/viesman_adapter.log)

[vcontrold.log](https://github.com/misanorot/ioBroker.viessmann/files/3275705/vcontrold.log)

[vcontrold.xml.txt](https://github.com/misanorot/ioBroker.viessmann/files/3275734/vcontrold.xml.txt)

[vito.xml.txt](https://github.com/misanorot/ioBroker.viessmann/files/3275736/vito.xml.txt)

**Comment by misanorot** [comment]
Hi,

du scheinst in deiner Vito.xml eine Befehl abzufragen, der Vcontrold nicht bekannt ist. Schalte doch bitte die Log Ausgabe auf debug....

**Comment by XerXes777** [comment]
moin,
danke für deine Antwort.
Die Logausgabe steht auf y
Und die Logdatei habe ich im Anhang oben: vcontrold.log

Sobald ich ich die instanz in iobroker neustarte und meinem pi neustarte ( da ist vcontrold installiert) läuft es erstmal für ein paar minuten.
Bekomme ordentliche Werte bei z.B Partybetrieb.

vcontrold ist in der neusten version installiert.

**Comment by misanorot** [comment]
Hallo, 

Ich meinte die Instanz auf debug stellen.
Heartbeat kommt vom Adapter, dass muss so sein.

**Comment by XerXes777** [comment]
Okay ich habe eben gesucht, aber finde keine debug in den einstellungen der instanz.
Wo kann ich das einstellen ?

**Comment by misanorot** [comment]
Und?

**Comment by XerXes777** [comment]
Bis jetzt kam der Fehler nicht wieder. Bedeutet ich kann es noch nicht reproduzieren.
Ich lasse es erstmal so laufen. Es hat immer gedauert (1-2 Tage), bis der Fehler kam.
Ich beobachte es weiter.
Bis jetzt stimmen auch noch meine Werte (z.B. Partybetrieb).

**Comment by XerXes777** [comment]
Also der Fehler ist wieder da.
Anbei der Log:

[viessman_log_13_juni.log](https://github.com/misanorot/ioBroker.viessmann/files/3287645/viessman_log_13_juni.log)

**Comment by misanorot** [comment]
Irgendwie scheint bei dir was doppelt zu laufen. Aber um du kannst doch die Option Neustart bei zu vielen Fehlern machen?

**Comment by XerXes777** [comment]
Also ich habe nur einen iobroker und eine viessman instanz am laufen. vcontold wird nur vom viesmann adapter angesprochen. habe eben nochmal gecheckt. vcontrold liefert direkt die korrekten werte. gehe davon aus, das es am adapter liegt.
Diese option hatte ich schon mal an, aber das hat nix gebracht.
Was soll ich tun ?

**Comment by misanorot** [comment]
Hi,

Ich denke nicht das es am Adapter liegt. Es ist allerdings schwer aus der Ferne zu sagen an was es liegt, ich hoffe trotzdem wir finden ein Weg. 

Bitte ersetze die main.js, und mache in der Konsole bitte ein iobroker upload viessmann.

Lass ihn dann als debug ausgabe laufen und übersende mir die Log Daten.[
[main.js.zip](https://github.com/misanorot/ioBroker.viessmann/files/3289108/main.js.zip)

](url)

**Comment by misanorot** [comment]
Gibt es Neuigkeiten?

**Comment by XerXes777** [comment]
Nein noch nicht. Ich muss erstmal heraus finden wie das geht, was du oben beschrieben hast.

**Comment by misanorot** [comment]
Eigentlich alles richtig, da habe ich bestimmt einen Fehler eingebaut. Kannst du Mal den Log schicken

**Comment by misanorot** [comment]
Ich weiß warum. Schicke dir nachher ne neue Datei

**Comment by misanorot** [comment]
Hallo,

welche Version hast du aktuell installiert? 0.9.3 ? Falls ja, installiere mal bitte die von GitHub und ersetzte bitte die Datei nochmal. 

Danke

**Comment by misanorot** [comment]
[main.zip](https://github.com/misanorot/ioBroker.viessmann/files/3294092/main.zip)

**Comment by XerXes777** [comment]
Installiert ist die Version 0.9.2

**Comment by misanorot** [comment]
Dann install bitte die git version

**Comment by XerXes777** [comment]
Okay. habe die instanz und adapter gelöscht und installier nun die git version

**Comment by XerXes777** [comment]
Anbei das LOG vom 17.
Die Werte in den Objekte von iobroker stimmen noch.

[viessman_log_17_juni.log](https://github.com/misanorot/ioBroker.viessmann/files/3295207/viessman_log_17_juni.log)


Merkwürdig sind diese Zeilen oder?:

viessmann.0	2019-06-17 05:52:10.277	debug	, step: heartbeat
viessmann.0	2019-06-17 05:52:10.277	debug	VCONTROLD send: ERR: command unknown
viessmann.0	2019-06-17 05:52:10.267	debug	Next poll: heartbeat heartbeat

**Comment by misanorot** [comment]
Hi,

Gut jetzt weiß ich zumindest warum das mit der Error Option bei dir nicht klappt.

Genau das mit den Zeiten hat mich ja auch gewundert, jetzt weiß ich warum.

Ich mache eine neue Main.js und schicke sie dir zum Testen

**Comment by misanorot** [comment]
[main.zip](https://github.com/misanorot/ioBroker.viessmann/files/3296020/main.zip)

**Comment by XerXes777** [comment]
Also ich wollte jetzt die neue main.js einsetzten,
da ist mir aufgefallen, das meine Objekte immer noch korrekt wieder gegeben werden.
Also irgendwas ist jetzt besser.

**Comment by XerXes777** [comment]
Also ich lade dir mal den LOG von heute hoch, weil da sind wieder fehler passiert.

6:30 ist interessant, weil ich da den Partymodus mal gesetzt habe.
Danach ist die Verbindung unterbrochen.

6:37 Vctrld send ERROR: vctrld>ERR: command unknown
vctrld>

Und Habe 14x eine Statusänderung von dem Partybetrieb gehabt.
Sieht man anhand der meldung mit pushover: 
Das programm zum versenden ist einfach:
Wird auf die partymodus objekt getriggert und bei änderung verglichen mit 1 oder 0.
info: pushover.0 Send pushover notification: {"message":"Partybetrieb ist Ein","sound":"magic","title":"Heizung","priority":"0"}

Aber ich weiß mein Partybetrieb war die ganze zeit bis 14:30 an.
Das bedeutet das wieder ein ? in iobroker bei den Objekten stand. Also im Partybetrieb.
Und irgendwann konnte er wieder eine 0 oder 1 lesen von vcontrold.

[vcontrold_19.log](https://github.com/misanorot/ioBroker.viessmann/files/3307379/vcontrold_19.log)
[viessman_log_19_juni.log](https://github.com/misanorot/ioBroker.viessmann/files/3307380/viessman_log_19_juni.log)

Ich hoffe wir können das Problem lösen.
Nochmal vielen Dank für deine Hilfe.

mfg
Kevin

**Comment by XerXes777** [comment]
Ich schreibe das mal bewust in einem 2ten post.

der viesmann adapter hat mir gerade in den partymodus eine 1 geschrieben.
ich weiß aber zu 100% das er nicht an ist.
und habs sofort direkt über telnet geprüft.

`vctrld>debug on
vctrld>getPartybetrieb
DEBUG:Wed Jun 19 20:13:33 2019 : Command: getPartybetrieb
DEBUG:Wed Jun 19 20:13:33 2019 : Process 6635 tries to aquire lock
DEBUG:Wed Jun 19 20:13:33 2019 : Process 6635 got lock
DEBUG:Wed Jun 19 20:13:33 2019 : >FRAMER: open device /dev/ttyUSB0 ProtocolID 41
DEBUG:Wed Jun 19 20:13:33 2019 : Configuring serial interface /dev/ttyUSB0
DEBUG:Wed Jun 19 20:13:33 2019 : >SENT: 04

Message from syslogd@vcontrold at Jun 19 20:13:33 ...
 vito[6635]: Configuring serial interface /dev/ttyUSB0

Broadcast message from systemd-journald@vcontrold (Wed 2019-06-19 20:13:33 CEST):

vito[6635]: Configuring serial interface /dev/ttyUSB0

DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 05 (1970.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: received 05
DEBUG:Wed Jun 19 20:13:35 2019 : >FRAMER: framer_reset_actaddr framer_current_addr = FRAMER_LINK_STATUS(05) (was FFFF)
DEBUG:Wed Jun 19 20:13:35 2019 : >FRAMER: closed
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 16
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 00
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 00
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 06 (10.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: received 06
DEBUG:Wed Jun 19 20:13:35 2019 : >FRAMER: framer_reset_actaddr framer_current_addr = FRAMER_NO_ADDR (was FE05)
DEBUG:Wed Jun 19 20:13:35 2019 : >FRAMER: opened
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 41
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 05
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 00
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 01
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 23
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 03
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 01
DEBUG:Wed Jun 19 20:13:35 2019 : >SENT: 2D
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 06 (20.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: received 06
DEBUG:Wed Jun 19 20:13:35 2019 : >FRAMER: framer_set_actaddr framer_current_addr = 0323 (was FFFF)
DEBUG:Wed Jun 19 20:13:35 2019 : >FRAMER: Command send
DEBUG:Wed Jun 19 20:13:35 2019 : >FRAMER: no preset result
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 41 (0.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: received 41
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 06 (0.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: received 06
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 01 (10.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 01 (0.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 23 (0.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 03 (0.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 01 (10.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 00 (0.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: len=1 2F (0.0 ms)
DEBUG:Wed Jun 19 20:13:35 2019 : <RECV: received 01 01 23 03 01 00 2F
DEBUG:Wed Jun 19 20:13:35 2019 : >FRAMER: framer_reset_actaddr framer_current_addr = FRAMER_NO_ADDR (was 0323)
DEBUG:Wed Jun 19 20:13:35 2019 : 00 -> 0
DEBUG:Wed Jun 19 20:13:35 2019 : 0
0
`

**Comment by misanorot** [comment]
Hi,

ich denke ich bin ein Stück weiter. Anscheinend bockt deine Verbindung wenn du Werte setzen willst. 6:30 ist genau das passiert. Der Adapter hat die Verbindung unterbrochen und neu gestartet. Alles soweit erstmal okay.... hier habe ich aber einen kleinen Fehler entdeckt. Probier bitte die neue Datei aus und gib mir Feedback. Danke


[main.zip](https://github.com/misanorot/ioBroker.viessmann/files/3317752/main.zip)

**Comment by misanorot** [comment]
Kannst auch für GitHub Version installieren

**Comment by misanorot** [comment]
Gibt es Neuigkeiten?

**Comment by XerXes777** [comment]
Nein gibt es noch nicht, da ich eben erst zurück nach Hause gekommen bin.
Habe deine neue main.js eben installiert. Und müssen jetzt nochmal abwarten.
Würde aber dennoch gerne wissen, warum die Verbindung abgebrochen ist.
Mein Pi ist via WLAN im Netztwerk eingebunden, könnte das das Problem sein?
Mitn Handy habe ich dort unten im Keller guten WLAN Empfang.

**Comment by misanorot** [comment]
Hi,

Vielleicht kommt das immer beim setzten von Werten. 

Hast du jetzt nochmal Infos für mich?

**Comment by XerXes777** [comment]
Ja habe ich.
Ich bin immer noch am schauen, was das Problem ist.
Ich bin auch der Meinung, sobald ich einen Wert setzten möchte, passieren die Fehler.
In dem LOG hatte ich eine Nacht kein Internet. Dies war aber mein Problem.

[LOG_mainjs_neu.zip](https://github.com/misanorot/ioBroker.viessmann/files/3371051/LOG_mainjs_neu.zip)

**Comment by misanorot** [comment]
Kannst du Mal bitte die aktuelle Version installieren, am besten komplett neu. Ich habe irgendwie das Gefühl das du noch mit der alten Version der main.js arbeitest.

Eigentlich sollte der Fehler der Mehrfachverbindung behoben sein, laut deiner Log Daten ist das aber nicht der Fall. Daher bitte Update machen und mir berichten. Danke.

**Comment by XerXes777** [comment]
So hab jetzt version 1.0.1 von git installiert und eine neue Instanz erstellt.
So ich wieder eine andere main.js nehmen ?
Wenn ja, welche?

**Comment by misanorot** [comment]
Nein brauchst du nicht, einfach laufen lassen....

**Comment by misanorot** [comment]
Hi,

Gibt es Neuigkeiten? Würde den issue gern schließen.

**Comment by XerXes777** [comment]
Das verstehe ich nicht, ich habe vor einer Woche einen Comment hinterlassen.
Und ich wunder mich schon, warum du noch nicht geantwortet hast. Ich lade dir die Daten nochmal hoch.
Irgendwas muss da ja schief gelaufen sein.

**Comment by misanorot** [comment]
Darauf habe ich doch geantwortet. Installiere bitte den Adapter komplett neu von npm....also ganz regulär

**Comment by XerXes777** [comment]
Moin Moin,
entschuldige bitte die Wartezeit.
Ich habe aber letzte Woche am 18. einen Comment gemacht mit den neuen Logs.
Ka was da schief gelaufen ist.

Mir ist es weiterhin wichtig, das wir das Problem in den Griff bekommen.

Bin zu folgender Erkenntnis gekommen:
Solange ich keine Werte SETZE ist alles okay.
Sobald ich einen Wert setzte kommen die Fehler.
Die Fehler äußern sich so, das ich die GET Befehle nicht mehr ordentlich bekomme.
Und dann später die Verbindung komplett abbricht.

[Archiv.zip](https://github.com/misanorot/ioBroker.viessmann/files/3427984/Archiv.zip)

**Comment by misanorot** [comment]
Hi,

kannst du bitte die Angehängte main.js bitte tauschen und einen iobroker upload viessmann machen. Dann im debug modus laufen lassen und durch setzen des Wertes den Fehler erzeugen. Bitte dann denn Log senden. Danke
[main.zip](https://github.com/misanorot/ioBroker.viessmann/files/3465257/main.zip)

**Comment by misanorot** [comment]
Hi,

bitte den Adapter von GitHub installieren, ich denke ich habe das problem mit den Dopplungen gefunden.

**Comment by XerXes777** [comment]
Ja geht los

**Comment by misanorot** [comment]
Ich denke es dürfte erledigt sein....

**Comment by XerXes777** [comment]
Vielen dank für deine Mühe!!!
Ich habe das jetzt die letzten Tage getestet.
Und die Werte werden korrekt in den Objekten eingetragen.
Selbst nachdem ich ein Objekt auch mal gesetzt habe.

Lag das Problem denn an meiner WLAN Verbindung?
Oder woran lag das Problem?

**Comment by misanorot** [comment]
Hi,

Freut mich zu hören. Nein es war was im Code.
