### ISSUE TITLE
Adapter stops working from time to time

### ISSUE THREAD

**Issue by Goersch** [misanorot/ioBroker.viessmann#42]
I upgrade from 0.7.x to 1.0.1 several weeks ago. Since then the adapter stps reading data or writing to the objects. After restarting the adapter continues working. There are no error messages in the log. I have now setup the cron so the adapter is restarted ever x hours. That would be ok if the adapter reads and transmits the send data to the heater. Is it like this? Does the adapter read and transmit the send-data with startup?

**Comment by Goersch** [comment]
I upgrade from 0.7.x to 1.0.1 several weeks ago. Since then the adapter stps reading data or writing to the objects. After restarting the adapter continues working. There are no error messages in the log. I have now setup the cron so the adapter is restarted ever x hours. That would be ok if the adapter reads and transmits the send data to the heater. Is it like this? Does the adapter read and transmit the send-data with startup?

**Comment by Goersch** [comment]
I checked and unfortunately the adapter does not do an initial read/write of the IO values - it onl waits for changes or time triggers. Would be nice if an inital read/write with the start of the adapt would be added to the adapter. Thanks :) Georg

**Comment by misanorot** [comment]
To your first post. After a adapter restart the send commands at empty. For me it is important why you have the problems after the update. It is very helpful when you give me your logs during the time when the adapter stops working. Please let run your instance in debug modus.

**Comment by misanorot** [comment]
To the second post.....I can try to include it in a next version, but the problem is when you send a lot of commands in a row, the connection to right object is wrong.

**Comment by misanorot** [comment]
no comment --> close
