### ISSUE TITLE
Automatic start after disconnection

### ISSUE THREAD

**Issue by drtp** [misanorot/ioBroker.viessmann#43]
I love this adapter. For me, it works nearly flawlessly over years. However, there is one thing I would like to see.

After a restart of my Raspberry with vcontrold installed on it the adapter loses its connection and the respective ioBroker "light" turns yellow. Therefore, I would appreciate it when the adapter automatically does at least one restart after e.g. 10 minutes of losing its connection to vcontrold. Would this be possible?

Cheers,

Thorsten

**Comment by misanorot** [comment]
Hey,

thanks...

Can you install the GitHub version? I tried to solve the problem. This release should reconnect to the host every 5 minutes after a connection failure. I haven´t the opportunity.

**Comment by misanorot** [comment]
Done (Version 1.2.0)
