### ISSUE TITLE
Keine Verbindung zu vcontrold auf Raspberry Pi

### ISSUE THREAD

**Issue by Max0608** [misanorot/ioBroker.viessmann#44]
Hallo,
ich habe den Adapter auf meinem iobroker installiert. Ich kann auch problemlos die beidem xml Dateien über ssh laden und er erstellt alle Datenpunkte.
Leider verbindet er sich nicht mit der Heizung. Der Adapter bleibt immer gelb und im log kommt ein Timeout.
Auslesen der Heizung über telnet und vclient geht problemlos.
Habe ich irgendwas vergessen um dem Adapter mitzuteilen, dass vcontrold auf einem anderen Rechner läuft? Finde dazu aber nichts in der config.

Viele Grüße

**Comment by misanorot** [comment]
[
![Unbenannt](https://user-images.githubusercontent.com/23728622/65538927-b7ece980-df08-11e9-87f9-fc7715d0db53.PNG)
](url)

Falls noch fragen sind, öffne ich den issue wieder. Okay?

**Comment by ArchGithub** [comment]
Kann ich vcontrold auf der gleichen Raspberry wie den iobroker laufen lassen?

**Comment by misanorot** [comment]
Hallo, ja das geht.
