### ISSUE TITLE
Vctrld send ERROR: ERR: command unknown

### ISSUE THREAD

**Issue by tsvsj** [misanorot/ioBroker.viessmann#49]
Hi,

I've already seen #41, but may request is different. Would it be possible to log the command, that produced "command unknown"? I have several entries - more than 50 entries in less than 1 hour - in my log, but don't know which command triggered this warning. Most log lines contain the same message. For now I see two different codes in front of the message: `(1952)` and `(32413)`. I don't know, if that code has any meaning regarding the issue itself.

Thanks for your help!

**Comment by misanorot** [comment]
Hello,

I think yes, let the instance run in debug log mode and you get a lot of Infos... Hope it helps, shouldn't please reopen the issue.

**Comment by tsvsj** [comment]
Hi,

thanks for your fast response. 

I've already did that, but what I meant was to add the name of the command to the warn message, instead having the command in debug and the "error" as a warn message. There is no relation between both messages. I'm not sure about the ID in front of the messages...maybe something like a counter for the runs? However, each message in the same run has the same ID.

I was able to find the command, which causes the messages. It's weird for me, that some commands do not work, while others do, when the numbering is in line (i.e. `TempVListM1` is not available, while `TempVListM2` is).

Thanks for your help and your work with this great adapter!

**Comment by misanorot** [comment]
Hi,

to your first part, normally the debug log has a connection to the message. Next poll..... After that it, the adapter print out the response from vcontrold. That confused me a little bit. Can you send me a log file?

To your second part, I can not help you sorry. Suggestion, visit the vcontrold page.
