### ISSUE TITLE
Abfrage des Fehlerspeichers (nur Datum wird angezeigt)

### ISSUE THREAD

**Issue by dosordie** [misanorot/ioBroker.viessmann#52]
Hallo,

wenn ich die Option "Datenpunktwerte kürzen" auswähle wird mir bei den Fehlerspeicher Einträgen nur das Datum angezeigt.
Schalte ich die Option aus passen die Error Datenpunkte, aber der Rest ist natürlich kacke. 

Kann man das irgendwo umkonfigurieren? 

Protokoll: KW2

**Comment by misanorot** [comment]
Muss ich mir anschauen, kannst du ein Beispiel posten?

**Comment by dosordie** [comment]
So sieht es aus wenn Datenpunkte kürzen an ist:
2020-01-11
Und so wenn die Option aus ist.
2020-01-11T17:29:36+0200 Wartung (fuer Reset Codieradresse 24 auf 0 stellen) (0F)

Reicht dass, oder brauchst du noch mehr infos?

**Comment by dosordie** [comment]
Mir ist noch eine Kleinigkeit aufgefallen:

get.SystemTime liefert auch nur das Datum, die Uhrzeit wird weggekürzt
2020-09-14

**Comment by misanorot** [comment]
> So sieht es aus wenn Datenpunkte kürzen an ist:
> 2020-01-11
> Und so wenn die Option aus ist.
> 2020-01-11T17:29:36+0200 Wartung (fuer Reset Codieradresse 24 auf 0 stellen) (0F)
> 
> Reicht dass, oder brauchst du noch mehr infos?

Nein reicht. Danke

**Comment by misanorot** [comment]
Hallo,

bitte mal die aktuelle GitHub Version testen. Dazu muss der Adapter vorher deinstalliert werden.
Sollte das klappen, mache ich eine neue Version.

PS: bei mir sehen die Werte so aus... Mi,01.05.2019 11:50:24 Brennerstoerung Kessel (D1)

**Comment by dosordie** [comment]
Cool, funktioniert.
Dankeschön :) 

Jetzt steht "2020-01-11T17:29:36+0200 Wartung (fuer Reset Codieradresse 24 auf 0 stellen) (0F)" da.


Warum bei mir das Datum so formatiert ist weiß ich auch nicht. Glaub das war nach dem Update auf die letzte Github Version von vControld...

**Comment by misanorot** [comment]
Ok super
