### ISSUE TITLE
io-Broker Anbindung Viesmann Kesselsteuerung 

### ISSUE THREAD

**Issue by RaGoos** [misanorot/ioBroker.viessmann#53]
Hallo,
hab hier mal eine allgemeine Frage zur Anbindung einer Viesmann Gastherme Vitodens 300-W BH3HF mit internen RF-Modul WiFi Modul. Die Anlage hängt im internem WLAN mit Freigabe und kann auch über die APP ViCare über die Viesmann Cloud bedient und überwacht werden.

Kann über einen io-Broker diese Gastherme auch direkt ausgelesen und bedient werden ohne den Umweg über Internet und Viessmann Cloud/anmeldung?

Hat damit jemand damit Erfahrung?  Die Gastherme ist gerade 1 Jahr alt und wurde im Rahmen einer Heizungserneuerung eingebaut. 

   fragend....

RaGoos

**Comment by misanorot** [comment]
Kann ich nicht viel zu sagen, aber bestimmt. 
Dieser Adapter setzt einen funktionierende Vcontrold Installation voraus!
