### ISSUE TITLE
Status bleibt gelb

### ISSUE THREAD

**Issue by jahnfraatz** [misanorot/ioBroker.viessmann#55]
Moin Moin,
ich kämfe schon seit Tagen mit dem Adapter.
Er zeigt immer wieder diesen Fehler im log an:

(18695) check vito.xml structure TypeError: Cannot read property '0' of undefined

Ich habe die Datei schon neu formatiert etc, aber nichts geht.
Ich habe auch schon gegoogelt und getestet, komme aber zu keiner Lösung.

**Comment by misanorot** [comment]
Hallo,

dann passt die Struktur in der Datei nicht, diese muss wie in der Anleitung aufgebaut sein! 
Im Zweifelsfall erstmal die Datei bis auf ein zwei Abfragen reduzieren....

Falls du gar nicht weiter kommst, einfach nochmal melden.
