### ISSUE TITLE
Nach Änderung der XML Disconnect des Adapter.

### ISSUE THREAD

**Issue by ManuelK83** [misanorot/ioBroker.viessmann#60]
Hallo der Adapter läuft soweit. 
Wenn ich aber die VITO.XML ändere, etwas hinzufüge bricht die Verbindung ab.

Ich gehe so vor.
1. XML ändern.
2. Über Telnet in Vcontrold die neue XML einlesen.
3. Im IObroker Adapter neue XML einlesen.
4. Neu configurieren.
Sobald die erste Abfrage kommt. --> Disconnect.

Ich muss den Raspi neu starten.
Vcontrold mit Telnet kann ich noch die Daten abrufen.

Kann wer helfen?

mfg Manuel

**Comment by misanorot** [comment]
Bitte den Adapter mal auf DEBUG stellen, und mir die Logs schicken wenn die Situation eintritt. Denke aber nicht das das Problem vom Adapter kommt.

**Comment by misanorot** [comment]
Keine Antwort! close

**Comment by ManuelK83** [comment]
Hallo,

Sorry das ich mich erst jetzt melde.

Ich denke auch das dass Problem bei vcontrold liegt.
Habe gerade keine zeit mich drum zu kümmern.

Melde mich nochmal fals ich nicht weiter kommen.

 Danke
frohe Weihnachten


Am So., 20. Dez. 2020 um 19:56 Uhr schrieb misanorot <
notifications@github.com>:
