### ISSUE TITLE
no existing object warnung mit js-controller 3.2.x version

### ISSUE THREAD

**Issue by Nunmalfix** [misanorot/ioBroker.viessmann#61]
viessmann.0 (19255) State "viessmann.0.get.Dummy" has no existing object, this might lead to an error in future versions

Einige Adapter werden Warnungen ausgeben wenn State-Werte gesetzt werden VOR dem Anlegen von Objekten. Bitte bei den Adapter-Repos melden - was hiermit geschehen ist ;-)

**Comment by misanorot** [comment]
Danke....

fixed in 1.3.3
