### ISSUE TITLE
js-controller 3.3.x

### ISSUE THREAD

**Issue by Nunmalfix** [misanorot/ioBroker.viessmann#62]
Seit dem Update auf js-controller 3.3.x kommen solche Warnungen im log:
warn: viessmann.0 (19188) Read-only state "viessmann.0.info.timeout_connection" has been written without ack-flag with value "false"
warn: viessmann.0 (19188) Read-only state "viessmann.0.info.lastPoll" has been written without ack-flag with value "1620048828"

**Comment by Nunmalfix** [comment]
Es gibt noch weitere Warnungen:
State value to set for "viessmann.0.get.BrennerStatus" has to be type "string" but received type "number"
State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"

**Comment by misanorot** [comment]
fixed in 1.3.4
