### ISSUE TITLE
js-controller 3.3.15

### ISSUE THREAD

**Issue by Linedancer** [misanorot/ioBroker.viessmann#69]
in der Version 1.3.4 hab ich immer noch folgende Meldungen:
State value to set for "viessmann.0.get.BrennerStufe" has to be type "string" but received type "number"
State value to set for "viessmann.0.get.PumpeStatusM1" has to be type "string" but received type "number"
State value to set for "viessmann.0.get.PumpeStatusSp" has to be type "string" but received type "number"
State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
Object of state "viessmann.0.set.NiveauM1" is missing the required property "common.type"

hab den Adapter gestoppt, alle DP gelöscht und Adapter wieder gestartet.

**Comment by misanorot** [comment]
Hi, die Werte stammen aus deiner xml Datei und werden so deklariert:

` switch (type){
        case 'enum':
            return 'string';
            break;
        case 'systime':
            return 'string';
            break;
        case 'cycletime':
            return 'string';
            break;
        case 'errstate':
            return 'string';
            break;
        case 'char':
            return 'number';
            break;
        case 'uchar':
            return 'number';
            break;
        case 'int':
            return 'number';
            break;
        case 'uint':
            return 'number';
            break;
        case 'short':
            return 'number';
            break;
        case 'ushort':
            return 'number';
            break;
        default:
            return 'mixed';`

Das mit dem set DP ist komisch, sollte eigentlich vom Typ gemischt sein.

**Comment by peoples0815** [comment]
Habe die gleichen Meldungen aber auch erst seit dem Update, das heißt ich muss die vito.xml nochmal in die Hand nehmen und sie wie du geschrieben hast anpassen?

**Comment by misanorot** [comment]
Die Vito muss entsprechend angepasst werden. Da wo die Fehler auflaufen muss entsprechend das Format angepasst werden. Theoretisch kann man das auch im Objektbaum machen, hat aber unter Umständen den Nachteil, dass bei einen Update o.ä. die Werte zurück gesetzt werden

**Comment by joerg2805** [comment]
Habe das selbe Problem wie Linedancer. Kannst Du bitte nochmal genau erklären, wo und was in der vito.xml geändert werden muss. Das o.g. switch (type) statement gibt es in meiner vito.xml nicht.

**Comment by misanorot** [comment]
> Habe das selbe Problem wie Linedancer. Kannst Du bitte nochmal genau erklären, wo und was in der vito.xml geändert werden muss. Das o.g. switch (type) statement gibt es in meiner vito.xml nicht.

Schick mal deine Datei, dann erkläre ich das.

Das mit dem switch stammt aus dem Adapter zu Deklaration der Typen

**Comment by joerg2805** [comment]
[vito.zip](https://github.com/misanorot/ioBroker.viessmann/files/7004792/vito.zip)

**Comment by peoples0815** [comment]
Bitte das Beispiel dann hier wieder einstellen zur Erklärung, Danke

**Comment by misanorot** [comment]
Bitte etwas Geduld, danke

**Comment by misanorot** [comment]
Hallo,

ich musste mich selbst erstmal wieder damit beschäftigen, es ist doch schon recht lange her.

In der VITO.xml steht i.d.r. eine `<unit>UT</unit>` , in der VCONTROLD.xml stehen dann die passenden Einheiten! Z.B. `<type>int</type>
	   <entity>°C</entity>`
vom Type Interger, also Zahl und als Masseinheit Grad Celsius.

Es ist also wichtig auch die Vcontrold.xml mit hoch zu laden.

Diese Dinge:
`switch (type){ case 'enum': return 'string'; break; case 'systime': return 'string'; break; case 'cycletime': return 'string'; break; case 'errstate': return 'string'; break; case 'char': return 'number'; break; case 'uchar': return 'number'; break; case 'int': return 'number'; break; case 'uint': return 'number'; break; case 'short': return 'number'; break; case 'ushort': return 'number'; break; default: return 'mixed';`

verarbeite ich im Adapter, als Beispiel int --> number.

Ich hoffe geholfen zu haben.???

**Comment by joerg2805** [comment]
Hallo misanorot,
danke für die Erklärung. Krieg's trotzdem nicht hin.

Die Fehlermeldung lautet:
`viessmann.0 | 2021-08-22 08:19:16.987 | info | State value to set for "viessmann.0.get.StatusVentil" has to be type "string" but received type "number"`

In der vito.xml steht:
```
<command name='getStatusVentil' protocmd='getaddr'>
             <addr>0A10</addr>
             <len>1</len>
             <unit>RT</unit>
             <description>Ermittle den Status des Umschaltventils</description>
         </command>
```

In der vcontrold.xml steht:
```
	<unit name='ReturnStatus'>
	   <abbrev>RT</abbrev>
	   <type>enum</type>
	   <enum bytes='00' text='0'/>
	   <enum bytes='01' text='1'/>
	   <enum text='NOT OK'/>
	</unit>
```
In main.js vom Viessmann Adapter steht:
`switch (type){ case 'enum': return 'string'; break; case 'systime': return 'string'; break; case 'cycletime': return 'string'; break; case 'errstate': return 'string'; break; case 'char': return 'number'; break; case 'uchar': return 'number'; break; case 'int': return 'number'; break; case 'uint': return 'number'; break; case 'short': return 'number'; break; case 'ushort': return 'number'; break; default: return 'mixed';`

Warum gibt es trotzdem die Fehlermeldung?

**Comment by misanorot** [comment]
Hi,

weil der Controller die 0 und 1 als Zahl interpretiert. Ändere den Text in deiner Vcontrold doch einfach auf EIN und AUS.
`<enum bytes='00' text='AUS'/>
	   <enum bytes='01' text='EIN'/>`

**Comment by joerg2805** [comment]
Super, jetzt läuft es.
