### ISSUE TITLE
A lot of messages - has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by martinschm** [misanorot/ioBroker.viessmann#73]
Hi,

the log of iobroker is full of info messages reagarding a mixup pf the type of the variables. Happened after the update to js-controller 3.3 and Admin 5.x

viessmann.0 | Zeit | debug | Nachricht
-- | -- | -- | --
viessmann.0 | 2021-11-01 09:29:00.923 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:28:01.919 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:27:00.675 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:26:01.664 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:25:54.223 | info | State value to set for "viessmann.0.get.BetriebSparM1" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:25:49.094 | info | State value to set for "viessmann.0.get.PumpeStatusSp" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:25:46.086 | info | State value to set for "viessmann.0.get.PumpeStatusM1" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:25:32.140 | info | State value to set for "viessmann.0.get.BrennerStufe" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:25:00.709 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:24:00.920 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:23:01.924 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:22:00.672 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:21:01.692 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:20:54.162 | info | State value to set for "viessmann.0.get.BetriebSparM1" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:20:49.229 | info | State value to set for "viessmann.0.get.PumpeStatusSp" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:20:46.157 | info | State value to set for "viessmann.0.get.PumpeStatusM1" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:20:32.048 | info | State value to set for "viessmann.0.get.BrennerStufe" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:20:00.665 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:19:00.899 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:18:01.874 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:17:00.658 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:16:01.653 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:15:54.156 | info | State value to set for "viessmann.0.get.BetriebSparM1" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:15:49.227 | info | State value to set for "viessmann.0.get.PumpeStatusSp" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:15:46.217 | info | State value to set for "viessmann.0.get.PumpeStatusM1" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:15:32.043 | info | State value to set for "viessmann.0.get.BrennerStufe" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:15:00.628 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:14:00.837 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:13:01.829 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:12:00.664 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:11:01.654 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:10:54.170 | info | State value to set for "viessmann.0.get.BetriebSparM1" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:10:49.172 | info | State value to set for "viessmann.0.get.PumpeStatusSp" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:10:46.168 | info | State value to set for "viessmann.0.get.PumpeStatusM1" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:10:32.045 | info | State value to set for "viessmann.0.get.BrennerStufe" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:10:00.685 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:09:00.911 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:08:01.881 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:07:00.649 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:06:01.782 | info | State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number"
viessmann.0 | 2021-11-01 09:05:54.143 | info | State value to set for "viessmann.0.get.BetriebSparM1" has to be type "string" but received type "number"

**Comment by misanorot** [comment]
Hello, that's no problem with the adapter! To resolve these messages, you will need to modify your XML files.

**Comment by uelpenich** [comment]
Hello, 
I need a hint how to modify my XML file. 
I get this message "State value to set for "viessmann.0.get.StatusStoerung" has to be type "string" but received type "number" with all values having units like this:

>     <unit name="ReturnStatus">
>       <abbrev>RT</abbrev>
>       <type>enum</type>
>       <enum bytes="00" text="0"/>
>       <enum bytes="01" text="1"/>
>       <enum bytes="02" text="2"/>
>       
>       <enum bytes="03" text="2"/>
>       <enum text="NOT OK"/>
>     </unit>
> 

It looks like an unwanted automatik text to number conversion

Values having units like this work fine. 

>     <unit name="BetriebsArt">
>       <abbrev>BA</abbrev>
>       <type>enum</type>
>       <enum bytes="00" text="WW"/>
>       <enum bytes="01" text="RED"/>
>       <enum bytes="02" text="NORM"/>
>       <enum bytes="04" text="H+WW FS"/>
>       <enum bytes="03" text="H+WW"/>
>       <enum bytes="05" text="ABSCHALT"/>
>       <enum text="UNKNOWN"/>
>     </unit>

**Comment by misanorot** [comment]
Hallo,

es scheint so, als iob die 1,2 usw als Zahl interpretiert obwohl der state ein Typ String ist. Was machst du mit den Werten im Anschluss? Wäre es möglich in deiner XML statt der 1 z.b. EIN zu schreiben?

Sonst fällt mir als workaround nur eins ein, du musst die betreffenden States händisch auf "Number" oder "Mixed" stellen.

**Comment by uelpenich** [comment]
Danke für die die schnelle Antwort. 

> Was machst du mit den Werten im Anschluss? 
Ich will sehen, ob es der Heizung gut geht. 
(Wenn man die Werte in eine Historie schreiben will, um sie anschliessend in einem Diagramm zu visualisieren, ist die number Darstellung die bessere)

> Wäre es möglich in deiner XML statt der 1 z.b. EIN zu schreiben?
Ja. Die Werte sind Statusrückmeldungen vergleichbar mit dem zweiten Beispiel (Betriebsart). Nur scheint die Viessmann Doku noch nicht so bekannt zu sein, dass man die Bedeutung von 0 1 2 3 in Texte übersetzen kann, oder man verwendet die gleiche Unit für verschiedenartige Dinge. 
Frage: gibt es keine Möglichkeit, die text -> number Konversion zu verhindern? Eine besondere Schreibweise / Syntax im XML Dokument?

> Sonst fällt mir als workaround nur eins ein, du musst die betreffenden States händisch auf "Number" oder "Mixed" stellen.
Das möchte ich vermeiden, da die händischen Änderungen mit jedem Neueinlesen der XML Dateien wieder weg sind. 
Auch die XML Dateien möchte ich nach Möglichkeit original lassen.

**Comment by misanorot** [comment]
Du könntest in deiner XML Typcodierung, ein zusätzliches Typ anlegen, z.B. enum1. Diesen würde ich beim einlesen automatisch als Mixed erkennen.

**Comment by uelpenich** [comment]
> Du könntest in deiner XML Typcodierung, ein zusätzliches Typ anlegen, z.B. enum1. Diesen würde ich beim einlesen automatisch als Mixed erkennen.

Habe ich ausprobiert, funktioniert leider nicht. Habe ich etwas falsch verstanden oder falsch gemacht?
    <command name="getPumpeStatusM2" protocmd="getaddr">
      <addr>3906</addr>
      <len>1</len>
      <unit>RT</unit>
      <description>Ermittle den Status der Pumpe M2</description>
      <device ID="2053"/>
      <device ID="20CB">
        <addr>7665</addr>
        <len>1</len>
        <unit>RT</unit>
      </device>
    </command>

    <unit name="ReturnStatus">
      <abbrev>RT</abbrev>
      <type>enum1</type>
      <enum1 bytes="00" text="0"/>
      <enum1 bytes="01" text="1"/>
      <enum1 bytes="02" text="2"/>
      
      <enum1 bytes="03" text="2"/>
      <enum1 text="NOT OK"/>
    </unit>

> Sonst fällt mir als workaround nur eins ein, du musst die betreffenden States händisch auf "mixed" stellen.
Das funktioniert.

**Comment by misanorot** [comment]
Hi,
ich bin zwar nicht der Experte für die XML s, aber ich denke das sieht gut aus. Wichtig, du musst die Dateien neu in den Adapter einlesen! Am besten vorher die States löschen

**Comment by uelpenich** [comment]
> ich bin zwar nicht der Experte für die XML s, aber ich denke das sieht gut aus.

Leider nicht. 

> Wichtig, du musst die Dateien neu in den Adapter einlesen! Am besten vorher die States löschen

Habe ich gemacht: 
1. Adapter Instanz angehalten
2. Objektbaum "Viessmann" komplett gelöscht
3. xml Datei geändert
4. Reboot
5. vito.xml neu einlesen gesetzt
6. Adapter Instanz neu gestartet
7. entsprechende Objekte und Protokolle kontrolliert

![grafik](https://user-images.githubusercontent.com/63613798/175021718-ffa2d7b5-3f7d-4d45-b54e-46f0dfa7004a.png)

> Du könntest in deiner XML Typcodierung, ein zusätzliches Typ anlegen, z.B. enum1. Diesen würde ich beim einlesen automatisch als Mixed erkennen. 

Mit meinen bescheidenen Programmierkenntnissen habe ich keine Idee, warum beim Einlesen des Typs enum1 etwas anderes passieren soll als beim Typ enum (oder habe ich doch etwas übersehen oder vergessen?)
An dieser Stelle würde ich auch nichts ändern, denn der Einlesevorgang macht genau das was in der xml definiert ist: ein Objekt vom Typ string / Text erstellen. 
Das Problem liegt bei der Übernahme der Echtzeit Daten, wo Text="0" abgeliefert und Integer=0 verstanden wird. 
Eigentlich gefällt mir dieses Verhalten, denn dann kann ich diese Daten über eine Historie (mariadb) in ein Diagramm (echart) weiter verarbeiten und in Diagrammen zeitlich darstellen. 
Es stört halt nur (wie bei [martinschm](https://github.com/martinschm) das Volllaufen der Logdatei.   
Ich werde die Protokollebene für meinen Viessmann Adapter auf Warnung zurückstellen. 
![grafik](https://user-images.githubusercontent.com/63613798/175025023-c8909c38-b9a3-46b0-bd38-78bf552ce486.png)

Vielen Dank für die Unterstützung.

**Comment by uelpenich** [comment]
Ja gerne, Das sind "serienmäßige" xml's von [https://github.com/openv/vcontrold/blob/master/xml/300/vcontrold.xml](url) und [https://github.com/openv/vcontrold/blob/master/xml/300/vito.xml](url), die ich für meinen Optolink Adapter (Ethernet) angepasst habe. Mein Viessmann Heizkessel ist ein "VScotHO1 B3HA-26 ID=20CB Protokoll:KW,300". 

Beobachtung:
Obwohl ich in der vcontrold.xm die DeviceID <device ID="20CB"/> angegeben habe, wird bei der Information zur Heizungsanlage etwas anderes angezeigt:
![grafik](https://user-images.githubusercontent.com/63613798/175241888-c5e8bf77-6d26-4b68-b83c-2bc4a8c827be.png)
Das ist (zufällig?) die erste Zeile der Mehrgeräte vito.xml:
![grafik](https://user-images.githubusercontent.com/63613798/175244411-039a9456-8701-467a-9272-3a5cc643531f.png)


[vito.zip](https://github.com/misanorot/ioBroker.viessmann/files/8965083/vito.zip)

Beobachtung:
Dieses Problem scheint immer noch zu existieren. Ich bekomme die SET Objekte nur, wenn ich die XMLs an beiden Stellen hinterlege. Weitere Baustelle: ich habe bisher noch keinen Wert setzen können. 
![grafik](https://user-images.githubusercontent.com/63613798/175244741-ceb66d41-e1e2-42b6-80c5-59cda0653f19.png)

Danke für die Unterstützung und sag mir, was ich ändern bzw. testen soll.

**Comment by misanorot** [comment]
Hi,

ich weiß zwar nicht wo du den letzten Screenshot gemacht hast, aber das ist eigentlich die alte Beschreibung. Bitte ließ die aktuelle Beschreibung, dort sieht man auch, dass nur ein device vorhanden sein sollte (ist aber nur zur richtigen Anzeige in der konfig Seite)

Ich lese die Tage deine XML Mal ein.

**Comment by uelpenich** [comment]
Ja, der Screenshot stammt von der alten Beschreibung. Ich habe nach einer Erklärung gesucht, warum bei mir keine SET Objekte angelegt worden sind. Unter dem Strich lag es daran, dass ich "Nur Werte anlegen die man benutzt" ausgewählt habe. Ich bin nicht auf die Idee gekommen, dass das auch für die SET Werte gilt. 
Frage: was macht die Option "Datenpunktwerte kürzen" (ist nirgendwo beschrieben).
![grafik](https://user-images.githubusercontent.com/63613798/175306238-5c72f493-8a59-4df5-b037-a1adefd0a0a2.png)

> Bitte lies die aktuelle Beschreibung, dort sieht man auch, dass nur ein Device vorhanden sein sollte 

Das habe ich da nicht herausgelesen, weil

- mit dem vcontrold komplette XML Dateien für mehrere Devices mitgeliefert werden
- in Deiner Beschreibung "Die Struktur der vito.xml muss in der folgenden Form aufgebaut sein:" nur beispielhaft ein Ausschnitt aus einer XML Datei gezeigt wird. Mit deiner Beschreibung ist man nicht in der Lage, die XML Dateien neu zu erstellen (es ist auch nicht deine Aufgabe, das zu beschreiben, das ist Aufgabe der vcontrold Kollegen).

**Comment by misanorot** [comment]
Hallo,

habe mir das nochmal angeschaut, du musst natürlich wo das der fall ist auch den Aufruf ändern. 

Z.B. auch RT1

`<command name="getStatusStoerung" protocmd="getaddr">
      <addr>7579</addr>
      <len>1</len>
      <unit>RT1</unit>
      <description>Status Sammelstoerung</description>
      <device ID="2053"/>
      <device ID="20CB">
        <addr>0A82</addr>
        <len>1</len>
        <unit>RT</unit>
      </device>
    </command>`

und dann in der vcontrold.xml auch die unit anlegen....

`<unit name="ReturnStatus">
  <abbrev>RT1</abbrev>
  <type>enum1</type>
  <enum1 bytes="00" text="0"/>
  <enum1 bytes="01" text="1"/>
  <enum1 bytes="02" text="2"/>
  
  <enum1 bytes="03" text="2"/>
  <enum1 text="NOT OK"/>
</unit>`

Zum Thema set Datenpunkte, diese werden selbstverständlich immer angelegt! Unabhängig von der der Option "Nur Datenepunke anlegen..."

**Comment by uelpenich** [comment]
> habe mir das nochmal angeschaut, du musst natürlich wo das der fall ist auch den Aufruf ändern.

Ich habe eine existierende Unit abgeändert. Der Aufruf im Command "getStatusStoerung" ist geschachtelt, d.h. steht in der Ausnahme für 20CB Devices. Bist du sicher, dass dein Konvertierungsprogramm die Ausnahme für mein 20CB Device verarbeitet hat und nicht nur die übergeordnete allgemeine Definitiion?
![grafik](https://user-images.githubusercontent.com/63613798/175810339-d4d3a15c-a7a2-4c07-b665-3fd8819e79d7.png)

Ich habe ein Verständnisproblem damit, dass es mit einem neuen Typ "enum1" funktionieren soll. In [https://github.com/openv/openv/wiki/vcontrold.xml](url) wird "enum" als Schlüsselwort für einen Aufzählungstyp beschrieben:

> enum -> Aufzählungstypen (Übersetzung Bytes in Text), Es können beliebige Bytefolgen (in Hex, Leerzeichen getrennt) angegeben werden.

Ist es sicher, dass der vcontrold sowie der vclient noch richtig funktionieren, wenn man einen neuen Typ "enum1" deklariert?

==> mein Vorschlag: lass alles so wie es ist und schliesse diesen Thread. Die mich (und [martinschm](https://github.com/martinschm)) störenden vielen Log Einträge kann man ganz einfach dadurch abschalten, in dem man die Logs der Adapterinstanz auf "warn" zurücknimmt. 
==> wenn du unbedingt etwas verbessern willst, dann übersetze doch alle "enum" Typen in Objekte vom Typ "mixed". 

PS: Bei dem Durchsuchen von vcontrold.xml Beispielen bin ich auf die folgende Unit Definition gestoßen. Mir sind die Semikolons in den Aufzählungen (mit Ausnahme von bytes="00" ?!?) aufgefallen. Hast du eine Idee was die Semikolons machen?

>     <unit name="ReturnStatus">
>       <abbrev>RT</abbrev>
>       <type>enum</type>
>       <enum bytes="00" text="0"/>
>       <enum bytes="01" text="1;"/>
>       <enum bytes="02" text="2;"/>
>       
>       <enum bytes="03" text="3;"/>
>       <enum text="NOT OK"/>
>     </unit>
>
