### ISSUE TITLE
Set befehle iobroker sofort senden

### ISSUE THREAD

**Issue by ManuelK83** [misanorot/ioBroker.viessmann#79]
Hallo,
ich würde gerne die Set Befehle sofort senden können. Ich habe gelesen das dies möglich ist. 
Finde aber nicht den Befehl, Anleitung dazu.

Kann das einer kurz erklären.

Danke

**Comment by misanorot** [comment]
Hallo,

sorry, ich habe deinen Post eben erst entdeckt. Schaue mir das die Tage an...

**Comment by misanorot** [comment]
Hallo,

so, musste mich erstmal mit dem Code beschäftigen. Es sieht folgendermaßen aus, die SET Befehle haben die höchste Priorität und werden vorrangig bearbeitet.  Die Zeit ergibt sich durch den kleinstes Abfrageintervall. Jedoch höchsten 60sek.

**Comment by ManuelK83** [comment]
Hallo,
ja das weiss ich das der set Befehl beim Abfragen ausgeführt wird. Ich dachte nur irgendwo gelesen zu haben, dass man ihn direkt  senden kann.
Es gibt ja auch den viessmann.0.input.force_polling_interval  Datenpunkt.  Was kann man damit anstellen ?

**Comment by misanorot** [comment]
Hi,

Damit kannst du direkt einen forcierten Wert anfragen. Z.b. du fragst die Brennerstunden nur einmal am Tag ab, willst sie aber zwischendurch nochmal bestimmen, dann kannst du diese Datenpunkt benutzen.

**Comment by ManuelK83** [comment]
OK alles klar. 
Also werde ich bei einem Get Befehl den intervall auf 1 Min einstellen und damit leben müssen ?

**Comment by misanorot** [comment]
Hallo, nein das brauchst du nicht. Ich habe eine Heartbeat von 60sek. In dem Adapter programmiert. Die 60sek sind ja wirklich nur die längste Annahme, es ist wahrscheinlich das die Zeit deutlich kleiner ist wenn du den Befehl absetzt. Wenn du mir ein use to für eine kleiner benötigte Zeit für Setzbefehle aufzeigt, könnte ich mich evtl. damit beschäftigen.

Eine ander Variante, du gibst den Setzbefehle ab und beschreibst hinterher den Force Datenpunkt. punkt

**Comment by ManuelK83** [comment]
Ah ok. passt schon. 
Wie sieht das aus wenn man  Alle Minute die Datenpunkte abfragt. Stresst das viel die Viessmann Steuerung ?

**Comment by misanorot** [comment]
Naja ich sag's Mal so, die Fehler werden bei sehr kleinen Abfrageintervallen grosser.

**Comment by ManuelK83** [comment]
ok dann bin ich erstmal zufrieden. :-) 
Danke für deine Zeit.

**Comment by besimo1** [comment]
Wie genau führe ich denn so einen Set-Befehl in ioBroker über z.B. Javascript aus - Beispiel mit z.B. Änderung der Soll-Temperatur oder Starten der Wasseraufbereitung" ?

P.S. Es werden mir viele Get-Werte angezeigt und ich kann diese nicht nur unter den Objekten sehen, sondern auch per javascript über einen Button in LoveLace abfragen. Nur eigentlich will ich über den Button die Sollwerte ändern bzw. idealerweise noch die Warmwasserbereitung starten (die WW-Bereitung konnte ich über den vclient gestern einmal starten - heute geht es nicht, da ich auch über den vclient heute irgendwie keine Werte mehr auslesen kann, obwohl sie in den ioBroker-Viessmann-Objekten weiterhin angezeigt werden)

Hier Mal mein Code mit allem, was ich ausprobiert habe:

on({id: '0_userdata.0.LoveLace.SetTempWWSoll2_55', val: true}, async function (obj) {
  
    setStateDelayed("0_userdata.0.LoveLace.SetTempWWSoll2_55", false, 1000, false);
   
    /* funktionierender Code - Gibt Temperatur in Debug-Fenster aus
    var i= getState("viessmann.0.get.TempA").val
    console.log(i);
    */

    var i= getState("viessmann.0.get.WWEinmal").val

    setState("viessmann.0.set.1xWWein.State",2);

    setState("viessmann.0.set.TempWWSoll2_55.State",55);/*TempWWSoll2 55*/
    //setState("viessmann.0.set.TempWWSoll2_55.State",true);/*TempWWSoll2 55*/
    //setState("viessmann.0.set.TempWWSoll2_55.State",1);/*TempWWSoll2 55*/

    var textList = "skrSetTempWWSoll2_55 wurde ausgeführt";

    console.log(textList);
});

**Comment by misanorot** [comment]
Hallo,

grundsätzlich sieht das mit dem setState richtig aus.

Bei allem ist aber die Voraussetzungen, dass deine Vito Datei auch richtig funktioniert.

Wenn du an den Viessmann Adapter einen Set Befehl sendest, kannst du das im Log sehen.

Des Weiteren ist es nicht sinnvoll neben der Adapter Verbindung zur Steuerung noch eine neue zu erstellen (vclient)

**Comment by besimo1** [comment]
Habe den Adapter gestoppt und testweise vclient probiert. Jetzt hat alles funktioniert wie es soll (Temperatursollwerte abrufen und setzen, 1xWWstarten).
Die vito.xml und die vcontrold.xml funktionieren also.
Ich denke mein Problem liegt darin, dass ich mit den Set-Befehlen in meinen xml-Dateien keine Werte übergeben muss (diese sind schon  in den Funktionen, die ausgeführt werden sollen vorhanden. Deswegen heissen sie z.b. "setTempWWSoll2_55" oder "set.TempWWSoll2_45". Mit dem Aufruf soll also die im xml-Code festgelegte Temperatur gesetzt werden, also hier 55° oder 45°. z.B. 46° ist in meinen xml-Dateien noch nicht eingebaut.
Der js-Befehl "setState" verlangt eine Variable bzw. einen Wert der übergeben werden soll. Aber eigentlich soll ja nur die Funktion aus meiner xml-Datei ausgeführt werden, da dort ja schon der Wert definiert ist, der an die Viessmann-Heizung übergeben wird.
In VBA würde man z.B. mit "Call" so eine Funktion aufrufen.
**Welchen Befehl muss ich hier verwenden ?**
(prinzipiell wäre es natürlich schöner, wenn man den Temperaturwert variabel eingeben könnte, aber dafür habe ich keine Vorlage für meine Vitocal 200-S mit Vitotronic 200 (W01C) - vermutlich ID 204D)

folgendes wird nicht akzeptiert (ich bin Neuling in Javascript):
   viessmann.0.set.TempWWSoll2_55;
   setState("viessmann.0.set.TempWWSoll2_55");

**Auszug aus vito.xml:**
`		<command name="getTempWWSoll2" protocmd="getaddr">
			<addr>600C</addr>
			<len>2</len>
			<unit>UT</unit>
			<description>Bedienung WW - Betriebsdaten WW: Zweiter Sollwert (10..60 (95))</description>
		</command>
		<command name="setTempWWSoll2_55" protocmd="setaddr55">
			<addr>600C</addr>
			<len>2</len>
			<unit>UT</unit>
			<description>Bedienung WW - Betriebsdaten WW: Zweiter Sollwert (10..60 (95))</description>
		</command>
		<command name="setTempWWSoll2_45" protocmd="setaddr45">
			<addr>600C</addr>
			<len>2</len>
			<unit>UT</unit>
			<description>Bedienung WW - Betriebsdaten WW: Zweiter Sollwert (10..60 (95))</description>
`
**Auszug aus vcontrold.xml:**
`
  <protocols>
      <protocol name='P300'>
          <pid>41</pid>
          <macros>
                <macro name='GETADDR'>
                    <command>SEND 00 01</command>
                </macro>
          </macros>
          <commands>
                <command name="getaddr">
                     <send>GETADDR $addr $hexlen;RECV $len $unit</send>
                <command name="setaddr45">
                     <send>SEND 00 02 $addr $hexlen C2 01;RECV 2 SR</send>
                </command>
                <command name="setaddr55">
                     <send>SEND 00 02 $addr $hexlen 26 02;RECV 2 SR</send>
                </command>
                <command name="setaddr">
                     <send>SEND 00 02 $addr $hexlen BYTES;RECV 1 SR</send>
                </command>
 `

**Comment by besimo1** [comment]
![image](https://user-images.githubusercontent.com/101955988/160475078-a2ff520a-a13e-471a-9e06-a5b0ff22ebec.png)

![image](https://user-images.githubusercontent.com/101955988/160475273-fa46ff81-2c75-46d1-89db-e700e2549fb5.png)

**Comment by besimo1** [comment]
Ich hatte vergessen, den Viessmann-Adapter vor dem Start des Skripts wieder zu aktivieren

hier nun das Protokoll bei eingeschaltetem Adapter (Ergebnis aber weiter unverändert - keine Soll-Temperaturänderung):
![image](https://user-images.githubusercontent.com/101955988/160477529-ae6f5116-4094-4972-bffe-9418719e5a9e.png)

**Comment by besimo1** [comment]
Übrigens, wenn ich in meinem Code "setstate("Viesmann...") ersetze durch:

exec("vclient -h 127.0.0.1:3002 -c setTempWWSoll2_55")

und den Viessmann-Adapter pausiere (was eigentlich nicht das Ziel ist), dann wird die Soll-Temperatur geändert.

**Comment by misanorot** [comment]
Hallo,

sicher das der Datenpunkt vorhanden ist? Laut Log ist das nicht der Fall. Vielleicht ein Copy Paste  Fehler mit Leerzeichen?

**Comment by besimo1** [comment]
Ich schaue heute abend nochmal nach. In den Screenshots kann ich jetzt erstmal keine Fehler entdecken.
Ist denn das true so richtig ?
Oder muss statt "true" eine "0" hin ?
Oder muss ich für den Setzdatenpunkt unter Objekten im Viessmann-Adapter Javascript aktivieren (so wie ich das bei den Ablese-Datenpunkten für Influxdb und LoveLace gemacht habe ?)

**Comment by misanorot** [comment]
Hallo,

wie du den Datenpunkt beschreiben musst, kann ich dir nicht sagen. Eigentlich ist das deinen Dateien zu entnehmen.

Aktivieren brauchst du nichts. Die Datenpunkte die unter Set stehen, sind auch beschreibbar.

**Comment by besimo1** [comment]
Datenpunkt ist vorhanden in der Viessmann-API:
![image](https://user-images.githubusercontent.com/101955988/160606233-665a1752-3bbd-4501-8f15-2878b81f61cd.png)

**Ausschnitte aus Vcontrold.xml:**
![image](https://user-images.githubusercontent.com/101955988/160607037-fda8693f-65c8-4ac6-b9c3-9b4b743d3672.png)

![image](https://user-images.githubusercontent.com/101955988/160607392-62ae2d90-14bf-471d-9dca-e262eacb13cd.png)
...
![image](https://user-images.githubusercontent.com/101955988/160607498-62f88c49-4d17-4e85-a873-486cfd1c22bc.png)

**Ausschnitte aus vito.xml**
![image](https://user-images.githubusercontent.com/101955988/160607868-e7577253-fd2c-4d80-9f1a-20627bdd7666.png)

Ich werde daraus nicht schlau und weiss nicht, was nicht, wie ich die Set-Befehle mit dem Viessmann-Adapter /iobroker/javascript ausführen. Das ist für mich die entscheidende Stelle. Nur wenn diesen Zugriff auf die WP habe, kann ich sie steuern und energetisch optimieren.

**Comment by misanorot** [comment]
Ich bin jetzt auch nicht der Experte was die xml's angeht, aber sollte grundsätzlich klappen.

Um Fehler beim Skripten auszuschließen, beschreibe erstmal die Datenpunkte direkt im Admin

**Comment by besimo1** [comment]
@misanorot 
Das verstehe ich nicht "...Datenpunkte direkt im Admin"

**Comment by besimo1** [comment]
So schaut der Datenpunkt unter Objekt-Objektdaten aus:
![image](https://user-images.githubusercontent.com/101955988/160661070-6579425e-1b00-445e-a539-2b5d643bbbc3.png)

Wo (Zeilennummer) kann ich hier welchen Code / Wert genau einfügen und wie wie wird dann der Code ausgeführt ?

**Comment by misanorot** [comment]
![image](https://user-images.githubusercontent.com/23728622/160672178-89485af9-dc20-4190-af2c-d0d144ff7922.png)

**Comment by besimo1** [comment]
@misanorot

Danke schonmal für die Unterstützung.

Aktueller Verlauf ist folgender:
1. System.Info-Adapter ist bei mir nicht gelaufen
2. node -Version 12.22.5 war installiert, npm war gar nicht installiert
3. Korrektur in myAdapter.js in Zeile 44 "objects." vor getObjectList entfernt -> danach ging System.Info
4. Datenpunkte direkt im Admin haben beim ersten Versuch funktioniert
5. Javascript "setState("viessmann.0.set.TempWWSoll2_55", 0);" hat einmal funktioniert mit Fehlermeldungen - u.a. diese unter Protokollen mit TempWWSoll2 not known - Datenpunkte direkt im Admin gingen dann nicht mehr
6. Neustart des viessmann-adapters - dann gingen die Datenpunkte direkt im Admin wieder - aber im Protokoll einige Fehler u.a. was mit npm
7. festgestellt npm fehlt
8. Versuch, node-Version 16.14.2 zu installieren - Ergebnis: ioBroker stürzt beim Start ab

Jetzt muss ich wohl ioBroker wieder neu installieren und ich weiss nach wie vor nicht, was ich bei der Installation über den Einzeiler mit curl ... falsch gemacht habe. Würdest du da nicht auch zum Image (aktuelle Version 1.3.0 vom 14.03.2022) raten ?
Dann sind zwar wieder meine influxdaten der letzten Woche weg, aber wichtiger ist mir ein funktionierendes sauberes System

**Comment by misanorot** [comment]
Hallo,

was die iobroker Installation angeht  bin ich sicherlich auch nicht die erste Adresse. Du findest hierzu im Forum aber gute Hilfestellungen. Iobroker bringt an sich ja schon einige Sachen mit um fehlerhafte Installationen zu beheben .

**Comment by besimo1** [comment]
Mittlerweile geht alles so wie oben beschrieben. Der Javascript-Code funktioniert.
Es lag wohl an zwei Fehlern, die bei insgesamt drei Neuinstallationen (sowohl per Einzeiler, als auch per Image) aufgetreten sind.
1. System.Info-Adapter ging nicht, weil man in der Datei myAdapters.js noch manuell "objects." vor objectlist löschen muss
2. nodejs war nicht mit npm verbunden. Dazu musste man wieder manuelle einen Einzeiler eintippen, wie es bei einer manuellen Node-Installation beschrieben wird.

Noch vielen Dank für die Unterstützung.

**Comment by misanorot** [comment]
Super... Kein Problem
