### ISSUE TITLE
warn im iobroker log

### ISSUE THREAD

**Issue by bahnuhr** [misanorot/ioBroker.viessmann#83]
Wenn man versucht die Betriebsart per Script zu ändern, kommen warn im log:

javascript.0 2022-06-19 10:10:00.904	warn	Read-only state "viessmann.0.get.BetriebArtM1" has been written without ack-flag with value "WW"
javascript.0 2022-06-19 10:10:00.903	warn	Object of state "viessmann.0.set.BetriebArtM1" is missing the required property "common.type"

Um dies zu verändern, müssen folgende Änderungen bei den DP vorgenommen werden:

DP: viessmann.0.get.BetriebArtM1
hier muss 	"write": true, 		gesetzt werden.

DP: viessmann.0.set.BetriebArtM1
hier muss 	"type": "string",	eingetragen werden.

**Comment by misanorot** [comment]
Hallo, 

die get States werden grundsätzlich nicht beschrieben! 

Zur zweiten Meldung, wie lange hast du den Adapter schon installiert? Wenn ich mich richtig erinnere, habe ich die Set states erst später mit einer Typisierung versehen. Es war bzw. Ist aber nötig die XML neu einzulesen.
