### ISSUE TITLE
vito.xml Datapoints do not show up in the Adapter Instance

### ISSUE THREAD

**Issue by dervitti** [misanorot/ioBroker.viessmann#84]
Hey,
while configuring your great adapter for the first time i ran into the situation, that nothing Abfragedatebpunkte or Setzdatenpunkte do show up in the Instance.
After setting the log settings to debug the log says:
> Copy vito.xml from server to host successfully
and a few lines later:
> read vito.xml successfull

The vcontrold runs on another machine. 

Am i doing something wrong?

```
native |  
-- | --
answer | false
states_only | false
errors | true
reconnect | "5"
new_read | false
ip | "192.168.0.23"
port | "3002"
user_name | "iobroker"
password | "is_correct_and_tested"
path | "/etc/vcontrold"
datapoints |  
gets | {}
sets | {}
system |  
-ID | "204D"
-name | "V200-S"
-protocol | "P300"

```

**Versions:**  
. Version 1.3.7 in /opt/iobroker/node_modules/iobroker.viessmann, node: v12.22.12, js-controller: 4.0.23
 - Operating system: Debian 9.13

**Additional context**  
[vito.xml.txt](https://github.com/misanorot/ioBroker.viessmann/files/9332132/vito.xml.txt)

Thank you for any hint.
best regards
Vitti

**Comment by dervitti** [comment]
Hi,
auch mit einer sehr einfachen vito.xml werden keine Datenpunkte im Adapter angelegt: 
```
<vito>
        <devices>
                <device ID="204D" name="V200-S" protocol="P300"/>
        </devices>
        <commands>
                <command name="Betriebsart" protocmd="getaddr">
                        <addr>B000</addr>
                        <len>1</len>
                        <unit>BA</unit>
                        <description>Bedienung HK1 Heizkreis 1 Wertebereich 0 - 4</description>
                </command>
        </commands>
</vito>
```

Die xml Dateien sind unter opt/iobroker/node_modules/iobroker.viessmann vorhanden und werden auch aktualisiert von vcontrold Host geholt, wenn der entsprechende Haken gesetzt wird.

**Comment by misanorot** [comment]
Hallo,

können Sie die vcontrold.xml auch hier hochladen? Auf Anhieb würde ich sagen, dass die vito okay aussieht.

Bitte mal die Instanz auf Debug stellen und dann den log posten.

**Comment by dervitti** [comment]
Hi, 
ich verwende folgende vcontrold.xml:  https://raw.githubusercontent.com/wiki/openv/openv/files/vcontrold_204D.xml

Das Log findest Du hier:
[iobroker_viessmann_debug.txt](https://github.com/misanorot/ioBroker.viessmann/files/9385270/iobroker_viessmann_debug.txt)

Der vcontrold selbst läuft auch und lässt sich per vclient bedienen. Einen wirklichen "Fehler" sehe ich im Log auch nicht....  
Oder habe ich einen Schritt beim Setup übersehen?

Hatte die Tage auch mal den Adapter auf 1.3.2 downgegradet, das brachte aber keine erkennbare Veränderung.
Danke für Deinen Support!

**Comment by misanorot** [comment]
Hi,

nach langen Suchen habe ich den Grund gefunden!

Das einlesen der Datenpunkte geht nur, wenn diese mit get oder set anfangen.
Bis jetzt ist das aber noch keinem aufgefallen. Eine Änderung dieser Verfahrensweise, wäre nur mit hohem Aufwand möglich.

Du müsstest also eine get o. set vor deine Namen einfügen....

`<command name='getTempAbgas' protocmd='getaddr'>`

**Comment by dervitti** [comment]
Hi,
Mega, vielen Dank! Ich hatte noch ein paar Commands mit Klammern im Namen, da ist der Import auch drüber gestolpert, aber als auch die wegwaren und alle gets auch mit "get" anfangen stehen nun alle Datenpunkte auch im Adapter! 

```
 <command name="getVerdichter2(Schuetz)" protocmd="getaddr">
                        <addr>0481</addr>
                        <len>1</len>
                        <unit>RT</unit>
                        <description>Diagnose Anlagenuebersicht Wertebereich 0 - 1</description>
                </command>
                <command name="getPrimaerquelle2(Primaerpumpe)" protocmd="getaddr">
                        <addr>0483</addr>
                        <len>1</len>
                        <unit>RT</unit>
                        <description>Diagnose Anlagenuebersicht Wertebereich 0 - 1</description>
                </command>
```




Vielen Dank!
VG
Vitti
