### ISSUE TITLE
Objects not shown. Wrong informations of the heating

### ISSUE THREAD

**Issue by Peter71131** [misanorot/ioBroker.viessmann#85]
**Describe the bug**  
Sorry if i probably feedback a user problem, but maybe somebody could tell me where to fix my problems.
I have three Issues at the Moment.

1. it seems the wrong heating is shown. I configured the 
[vcontrold.xml](https://github.com/misanorot/ioBroker.viessmann/files/9398182/vcontrold.txt)
 with 20CB Device ID.
    But it showes me something like that
![image](https://user-images.githubusercontent.com/50030738/186033441-a3caaa5b-c875-46cd-a007-e979700a4f62.png)
Why?

2. In the objects i can't find the Objects like TempA or TempKol from [vito.xml](https://github.com/misanorot/ioBroker.viessmann/files/9398179/vito.txt)

![image](https://user-images.githubusercontent.com/50030738/186033836-29fcaaff-54b3-4ed6-b34e-1b54d09d42f3.png)
 
3. Why all the Objects are existing if i only configured one for example.
![image](https://user-images.githubusercontent.com/50030738/186034107-c5e01ec8-5700-4948-85b3-21290b221597.png)
![image](https://user-images.githubusercontent.com/50030738/186034272-c105df4e-dcf9-4c42-8a40-5597720c8124.png)
What the meaning of this setting? 
![image](https://user-images.githubusercontent.com/50030738/186034550-c0d00114-2718-47ba-994b-fa1161d28274.png)

Attached my Debug Log.
[iobroker_viessmann_debug.txt](https://github.com/misanorot/ioBroker.viessmann/files/9398200/iobroker_viessmann_debug.txt)

Could somebody tell me what i need to do?
Thanks in advance.
Greetings
Peter

**Comment by Peter71131** [comment]
okay point2 seems solved somehow.
Maybe its only one times there after i read the datas in?

**Comment by misanorot** [comment]
Hallo,

zu 1. Die Daten kommen aus der vito.xml. Bitte diese anpassen, und so das am besten nur ein Gerät drin steht.

2. Versteh ich nicht

3. Es werden nur states angelegt, bei denen eine Zeit in der konfig konfiguriert wurde. Adapter Neustart notwendig.
