### ISSUE TITLE
Connection loss since 1.4.2

### ISSUE THREAD

**Issue by Issr4k** [misanorot/ioBroker.viessmann#96]
Gibts es für version 1.4.2 eine feste Anforderung an die Version von vcontrold?

Vcontrol läuft seit Wochen und Monaten nicht auf der neusten Version. Bis gestern hat alles funktioniert, dann habe ich den Adapter auf die 1.4.2 gezogen, seitdem bricht die Verbindung ständig ab und der Adapter wird gelb.
Manuelle neustarten (sudo vcontold -n) und anschließend neustarten des Adapters baut die Verbindung auf aber beim ersten Abfragen von Werten bricht die Verbindung wieder ab.
Eine Idee wonach ich schauen kann?

**Comment by misanorot** [comment]
Hallo,

im Zweifelsfall back to old version, oder mal den Adapter auf Debug stellen und mir die Ausgaben senden.

Den Vcontrold PC mal neu starten ist auch nicht verkehrt.

**Comment by Issr4k** [comment]
Neuinstallation auf die vcontrold v0.98.12 hat geholfen.

Klappt wieder alles.

Danke trotzdem!!!
