### ISSUE TITLE
warning beim setzen eines Wertes

### ISSUE THREAD

**Issue by goeran03** [misanorot/ioBroker.viessmann#97]
bein setzen des Objektes "TempWWsoll", das tritt nur bei diesem Objekt auf, kommt im Fehlerprotokoll:

warn Vctrld send ERROR: ERR: >FRAMER: unexpected length 2 02Fehler recv, AbbruchFehler beim ausfuehren von setTempWWsoll 14vctrld>
kurz vorher:

info | state viessmann.0.set.TempWWsoll changed: 14 (ack = false)

Ich verwende aber noch die 1.3.7 

Allerdings wird das Kommando ausgefuehrt. Ich sehe in der vito.xml dahingehend keine Auffälligkeit

**Comment by misanorot** [comment]
Hallo,

ist kein Fehler des Adapters, sondern die Antwort des Vcontrold Daemon. Gibst du vielleicht einen falschen Wert ein?

**Comment by goeran03** [comment]
der Wert im Beispiel oben war 14. Also nichts ungewöhnliches. Aber auch mit jedem anderen Wert passiert das.
Andere Temperatursollwert-Objekte beschweren sich nicht.

**Comment by misanorot** [comment]
Hi,

auf jeden Fall ist der Fehler Richtung Vcontrold zu suchen. Entweder die Dateien oder bei der Steuerung. Ich kann an dieser Stelle leider nicht weiterhelfen. Probiers doch mal auf der GitHub Seite von Vcontrol.
